const WebSocket=require("ws"), http=require("http"), fs=require("fs");
const OUT=process.argv[2];
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>res(JSON.parse(d)))}).on("error",rej));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const probe=new WebSocket("ws://localhost:8281"); let snap=null,pid=null;
  probe.on("open",()=>probe.send(JSON.stringify({t:"hello",session:"probe"})));
  probe.on("message",r=>{const m=JSON.parse(r); if(m.t==="welcome")pid=m.id; else if(m.t==="s")snap=m;});
  const t=(await get("http://localhost:9313/json")).find(x=>x.type==="page"&&x.url.includes("8281"));
  const cdp=new WebSocket(t.webSocketDebuggerUrl); await new Promise(r=>cdp.on("open",r));
  let id=0; const pend=new Map();
  cdp.on("message",m=>{const j=JSON.parse(m); if(pend.has(j.id)){pend.get(j.id)(j.result);pend.delete(j.id)}});
  const cmd=(me,p={})=>new Promise(r=>{const i=++id;pend.set(i,r);cdp.send(JSON.stringify({id:i,method:me,params:p}))});
  const ev=async e=>(await cmd("Runtime.evaluate",{expression:e,returnByValue:true})).result.value;
  const shot=async f=>{const r=await cmd("Page.captureScreenshot"); if(r&&r.data) fs.writeFileSync(`${OUT}/${f}`,Buffer.from(r.data,"base64"));};
  await cmd("Runtime.enable"); await cmd("Page.enable"); await sleep(3200);
  const hud=async()=>{const s=await ev(`document.getElementById("hud").textContent`);
    const z=parseFloat(s.match(/\(([\d.]+)x\)/)[1]);
    const [x,y]=s.split("\n")[1].split("  ")[0].split(",").map(Number); return {z,x,y}};
  const [W,H]=JSON.parse(await ev(`JSON.stringify([innerWidth,innerHeight])`));
  for(let i=0;i<5;i++){await cmd("Input.dispatchMouseEvent",{type:"mouseWheel",x:W/2,y:H/2,deltaX:0,deltaY:300});await sleep(140);}
  await sleep(800);
  const c=await hud();
  const mine=snap.ships.filter(s=>s.owner!==null&&s.owner!==pid);
  const scr=(x,y)=>[W/2+(x-c.x)*c.z, H/2+(y-c.y)*c.z];
  const press=async([x,y],ms)=>{
    await cmd("Input.dispatchMouseEvent",{type:"mousePressed",x,y,button:"left",buttons:1,clickCount:1});
    await sleep(ms);
    await cmd("Input.dispatchMouseEvent",{type:"mouseReleased",x,y,button:"left",buttons:0,clickCount:1});
  };
  const [A,B]=mine;
  await press(scr(A.x,A.y),60); await sleep(300);
  await press(scr(B.x,B.y),700); await sleep(500);
  const a2=snap.ships.find(s=>s.id===A.id), b2=snap.ships.find(s=>s.id===B.id);
  const gx=(a2.x+b2.x)/2, gy=(a2.y+b2.y)/2;
  const far=Math.max(Math.hypot(a2.x-gx,a2.y-gy), Math.hypot(b2.x-gx,b2.y-gy));
  const R=Math.max(far+90,130), ang=-Math.PI*0.75;
  const ip=scr(gx+Math.cos(ang)*R, gy+Math.sin(ang)*R);
  console.log(`  group circle r=${R.toFixed(0)} world; dismiss icon at screen ${ip[0].toFixed(0)},${ip[1].toFixed(0)}`);
  await shot("group_before.png");
  const before=snap.ships.filter(s=>s.owner!==null&&s.owner!==pid&&s.dx!==undefined).length;
  await press(ip,60); await sleep(600);
  await shot("group_after.png");
  await press([60,H-60],60); await sleep(900);
  const after=snap.ships.filter(s=>s.owner!==null&&s.owner!==pid&&s.dx!==undefined).length;
  console.log(`  after tapping dismiss, a tap in open space ordered: ${after-before} ships (want 0)`);
  process.exit(0);
})().catch(e=>{console.log("FAIL "+e.message.split("\n")[0]);process.exit(1)});
