const WebSocket=require("ws"), http=require("http"), fs=require("fs");
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>res(JSON.parse(d)))}).on("error",rej));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const probe=new WebSocket("ws://localhost:8283"); let snap=null,pid=null;
  probe.on("open",()=>probe.send(JSON.stringify({t:"hello",session:"probe"})));
  probe.on("message",r=>{const m=JSON.parse(r); if(m.t==="welcome")pid=m.id; else if(m.t==="s")snap=m;});
  const t=(await get("http://localhost:9315/json")).find(x=>x.type==="page"&&x.url.includes("8283"));
  const cdp=new WebSocket(t.webSocketDebuggerUrl); await new Promise(r=>cdp.on("open",r));
  let id=0; const pend=new Map();
  cdp.on("message",m=>{const j=JSON.parse(m); if(pend.has(j.id)){pend.get(j.id)(j.result);pend.delete(j.id)}});
  const cmd=(me,p={})=>new Promise(r=>{const i=++id;pend.set(i,r);cdp.send(JSON.stringify({id:i,method:me,params:p}))});
  const ev=async e=>(await cmd("Runtime.evaluate",{expression:e,returnByValue:true})).result.value;
  await cmd("Runtime.enable"); await cmd("Page.enable"); await sleep(3200);
  const hud=async()=>{const s=await ev(`document.getElementById("hud").textContent`);
    const z=parseFloat(s.match(/\(([\d.]+)x\)/)[1]);
    const [x,y]=s.split("\n")[1].split("  ")[0].split(",").map(Number); return {z,x,y}};
  const [W,H]=JSON.parse(await ev(`JSON.stringify([innerWidth,innerHeight])`));
  const c=await hud();
  const mine=snap.ships.filter(s=>s.owner!==null&&s.owner!==pid);
  const A=mine[0];
  const sx=W/2+(A.x-c.x)*c.z, sy=H/2+(A.y-c.y)*c.z;
  // count lit pixels in a box around the ship, to see whether an arc is being drawn
  const lit=async()=>ev(`(()=>{const cv=document.getElementById("c"),x=cv.getContext("2d");
    const dpr=cv.width/innerWidth, R=Math.round(90*dpr);
    const d=x.getImageData(Math.round(${sx}*dpr)-R, Math.round(${sy}*dpr)-R, 2*R, 2*R).data;
    let n=0; for(let i=0;i<d.length;i+=4) if(d[i+1]>90 && d[i]<160) n++;
    return n;})()`);
  const base=await lit();
  await cmd("Input.dispatchMouseEvent",{type:"mousePressed",x:sx,y:sy,button:"left",buttons:1,clickCount:1});
  await sleep(90);  const at90 =await lit();
  await sleep(210); const at300=await lit();
  await sleep(200); const at500=await lit();
  await cmd("Input.dispatchMouseEvent",{type:"mouseReleased",x:sx,y:sy,button:"left",buttons:0,clickCount:1});
  console.log(`  green pixels near the ship (baseline ${base}):`);
  console.log(`    90ms into the press  : ${at90}   ${at90<=base+40?"nothing drawn yet":"ARC ALREADY SHOWING"}`);
  console.log(`    300ms                : ${at300}  ${at300>base+40?"arc sweeping":"nothing"}`);
  console.log(`    500ms (press fired)  : ${at500}`);
  process.exit(0);
})().catch(e=>{console.log("FAIL "+e.message.split("\n")[0]);process.exit(1)});
